.PHONY: clean All

All:
	@echo "----------Building project:[ Broker - Debug ]----------"
	@cd "Broker" && "$(MAKE)" -f  "Broker.mk"
clean:
	@echo "----------Cleaning project:[ Broker - Debug ]----------"
	@cd "Broker" && "$(MAKE)" -f  "Broker.mk" clean
