.PHONY: clean All

All:
	@echo "----------Building project:[ Station_RPiZeroW - Debug ]----------"
	@cd "Station_RPiZeroW" && "$(MAKE)" -f  "Station_RPiZeroW.mk"
clean:
	@echo "----------Cleaning project:[ Station_RPiZeroW - Debug ]----------"
	@cd "Station_RPiZeroW" && "$(MAKE)" -f  "Station_RPiZeroW.mk" clean
