.PHONY: clean All

All:
	@echo "----------Building project:[ MOR - Debug ]----------"
	@cd "MOR" && "$(MAKE)" -f  "MOR.mk"
clean:
	@echo "----------Cleaning project:[ MOR - Debug ]----------"
	@cd "MOR" && "$(MAKE)" -f  "MOR.mk" clean
